import type { Metadata } from "next";
import Footer from './components/Footer'
import Navbar from './components/Navbar'
import { Montserrat } from "next/font/google";
import "./globals.css";

const inter = Montserrat({ weight:["100","300","400","700","500","900"],fallback:["inter"],subsets:["cyrillic"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
